version: '3.8'

services:
  app:
    build: .
    ports:
      - "127.0.0.1:5001:5001"
    depends_on:
      - db
      - redis
    volumes:
      - ./public:/root/public
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SERVER_ADDRESS=:5001
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    restart: always  # Add this line

  db:
    image: postgres:17rc1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "127.0.0.1:5433:5432"
    restart: always  # Add this line

  redis:
    image: redis:7.4.0-alpine
    ports:
      - "127.0.0.1:6380:6379"
    command: redis-server
    volumes:
      - redis_data:/data
    restart: always  # Add this line

  nginx:
    image: nginx:1.27.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl
    depends_on:
      - app
    restart: always  # Add this line

volumes:
  postgres_data:
  redis_data:
